sudo: required
language: java
jdk:
- openjdk8
before_script:
- wget http://services.gradle.org/distributions/gradle-5.5.1-bin.zip
- unzip gradle-5.5.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-5.5.1
- export PATH=$GRADLE_HOME/bin:$PATH
addons:
  chrome: stable
before_install:
- openssl aes-256-cbc -K $encrypted_82c0ba696085_key -iv $encrypted_82c0ba696085_iv
  -in environment.json.enc -out environment.json -d
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- gradle clean executeFeatures
notifications:
  email: true
